// Client-side route paths — one source of truth for navigation
export const ROUTES = {
  home:             '/',
  login:            '/login',
  register:         '/register',
  businessRegister: '/register/business',
  adminRegister:    '/register/admin',
  adminLogin:       '/login/admin',
  forgotPassword:   '/forgot-password',
  resetPassword:    '/reset-password',
  verifyOtp:        '/verify-otp',
  dashboard:        '/dashboard',
  profile:          '/profile',
  transfer:         '/transfer',
  deposit:          '/deposit',
  requery:          '/requery',
  kyc:              '/kyc',
  history:          '/history',
  businessDashboard: '/business/dashboard',
  // Admin
  adminDashboard:   '/admin/dashboard',
  adminCreateAdmin: '/admin/create-admin',
  adminCustomers:   '/admin/customers',
  adminKycQueue:    '/admin/kyc/pending',
  adminTransactions:'/admin/transactions',
  adminAuditLogs:   '/admin/audit-logs',
}
